/*
 * Hexabot — Fair Core License (FCL-1.0-ALv2)
 * Copyright (c) 2026 Hexastack.
 * Full terms: see LICENSE.md.
 */

import { MigrationInterface, QueryRunner } from 'typeorm';

import {
  deprovisionLexicalInfrastructure,
  provisionLexicalInfrastructure,
} from '@/extensions/helpers/fulltext-search/fulltext.provisioning';
import { SettingOrmEntity } from '@/setting/entities/setting.entity';

import { MigrationServices } from '../types';

const FULLTEXT_HELPER = 'fulltext-search';

/**
 * v3.4.0 removes the legacy (llamaindex-era) embedding-RAG footprint and
 * provisions the core lexical `fulltext-search` helper.
 *
 * Extension-owned storage and settings stay outside the core migration. This
 * migration only cleans up legacy structures, sets up lexical search, and
 * defaults RAG to the built-in `fulltext-search` helper.
 */
export default class Migration1784815200000_V3_4_0 implements MigrationInterface {
  name = 'Migration1784815200000_V3_4_0';

  public async up(
    queryRunner: QueryRunner,
    _services?: MigrationServices,
  ): Promise<void> {
    const databaseType = queryRunner.connection.options.type;

    // Drop any legacy plain (btree) index on contents."searchText". It was
    // created from an entity `@Index(['searchText'])` decorator that has since
    // been removed: on PostgreSQL it caps the column at ~2704 bytes and makes
    // inserting long content (required for RAG chunking) fail. `synchronize`
    // removes it automatically, but `synchronize=false` deployments need this.
    await this.dropSearchTextIndex(queryRunner);

    await provisionLexicalInfrastructure(queryRunner);

    if (databaseType === 'better-sqlite3' || databaseType === 'sqlite') {
      await this.dropLegacySqliteRagRemnants(queryRunner);
    }

    await this.seedDefaultRagHelper(queryRunner);
  }

  public async down(
    queryRunner: QueryRunner,
    _services?: MigrationServices,
  ): Promise<void> {
    await deprovisionLexicalInfrastructure(queryRunner);

    if (await queryRunner.hasTable('settings')) {
      const repository = queryRunner.manager.getRepository(SettingOrmEntity);
      await repository.delete({
        group: 'global_settings',
        label: 'default_rag_helper',
      });
    }
  }

  /**
   * Removes any single-column, non-constraint btree index on
   * contents."searchText". The index name is auto-generated by TypeORM, so it
   * is discovered from the catalog rather than hard-coded. The GIN full-text
   * index (an expression index) and the btree on "title" are left untouched.
   */
  private async dropSearchTextIndex(queryRunner: QueryRunner): Promise<void> {
    const databaseType = queryRunner.connection.options.type;

    if (databaseType === 'postgres') {
      const schema = (queryRunner.connection.options as { schema?: string })
        .schema;
      const rows = (await queryRunner.query(
        `SELECT n.nspname AS "schema", i.relname AS "name" ` +
          `FROM pg_index ix ` +
          `JOIN pg_class i ON i.oid = ix.indexrelid ` +
          `JOIN pg_class t ON t.oid = ix.indrelid ` +
          `JOIN pg_namespace n ON n.oid = t.relnamespace ` +
          `JOIN pg_am am ON am.oid = i.relam ` +
          `JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ix.indkey[0] ` +
          `WHERE t.relname = 'contents' AND a.attname = 'searchText' ` +
          `AND ix.indnatts = 1 AND am.amname = 'btree' ` +
          `AND NOT ix.indisprimary AND NOT ix.indisunique ` +
          (schema
            ? `AND n.nspname = $1`
            : `AND n.nspname = ANY(current_schemas(false))`),
        schema ? [schema] : [],
      )) as Array<{ schema: string; name: string }>;

      for (const row of rows) {
        await queryRunner.query(
          `DROP INDEX IF EXISTS "${row.schema.replace(/"/g, '""')}".` +
            `"${row.name.replace(/"/g, '""')}"`,
        );
      }
    } else if (databaseType === 'better-sqlite3' || databaseType === 'sqlite') {
      const indexes = (await queryRunner.query(
        `PRAGMA index_list("contents")`,
      )) as Array<{ name: string; origin?: string }>;

      for (const index of indexes) {
        // origin 'c' = created by CREATE INDEX (skip 'u'/'pk' constraint indexes)
        if (index.origin && index.origin !== 'c') {
          continue;
        }
        const info = (await queryRunner.query(
          `PRAGMA index_info("${index.name.replace(/"/g, '""')}")`,
        )) as Array<{ name: string }>;

        if (info.length === 1 && info[0].name === 'searchText') {
          await queryRunner.query(
            `DROP INDEX IF EXISTS "${index.name.replace(/"/g, '""')}"`,
          );
        }
      }
    }
  }

  /**
   * Removes the dormant llamaindex-era embedding-RAG remnants left inside the
   * SQLite database by the previous version: the `content_chunks` /
   * `content_embeddings` storage tables, the `content_chunks_fts` FTS5 mirror,
   * and — critically — the AFTER triggers on `contents` that keep writing into
   * them. Those triggers survive the upgrade and fire on every content
   * create/update/delete; worse, the old cleanup docs told operators to drop
   * `content_chunks`, which then made every content write fail with
   * `no such table: content_chunks`. Current RAG helpers use none of these, so
   * they are dropped outright.
   *
   * `DROP TABLE` on `content_chunks` also drops its own `content_chunks_fts_*`
   * triggers, and `DROP TABLE` on the FTS5 mirror removes its shadow tables
   * (_data/_idx/_docsize/_config). Triggers on `contents` must be dropped
   * explicitly and before the tables. All statements use `IF EXISTS`, so this
   * is idempotent and a no-op on databases that never ran llamaindex.
   */
  private async dropLegacySqliteRagRemnants(
    queryRunner: QueryRunner,
  ): Promise<void> {
    const contentsTriggers = [
      'content_chunks_after_content_insert',
      'content_chunks_after_content_update',
      'content_chunks_after_content_delete',
      'content_embeddings_after_content_delete',
    ];
    for (const trigger of contentsTriggers) {
      await queryRunner.query(`DROP TRIGGER IF EXISTS "${trigger}"`);
    }
    await queryRunner.query(`DROP TABLE IF EXISTS "content_chunks_fts"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "content_chunks"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "content_embeddings"`);
  }

  /**
   * Defaults RAG to the built-in lexical `fulltext-search` helper when no
   * selection exists yet. Existing selections are always preserved.
   */
  private async seedDefaultRagHelper(queryRunner: QueryRunner): Promise<void> {
    if (!(await queryRunner.hasTable('settings'))) {
      return;
    }

    const repository = queryRunner.manager.getRepository(SettingOrmEntity);
    const existing = await repository.findOne({
      where: { group: 'global_settings', label: 'default_rag_helper' },
    });

    if (!existing) {
      await repository.save(
        repository.create({
          group: 'global_settings',
          label: 'default_rag_helper',
          value: FULLTEXT_HELPER,
        }),
      );
    }
  }
}
